name: Build

on:
  pull_request:
  push:
    branches:
      - gha_co_jellyfish
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH agent to give GitHub Actions access to Torus-ZK/jellyfish
        id: configure-ssh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.ORG_PRIVATE_SSH_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null

          eval `ssh-agent -s`
          echo "${SSH_PRIVATE_KEY}" >> ~/.ssh/jellyfish_deploy_key
          chmod 0600 ~/.ssh/jellyfish_deploy_key
          ssh-add ~/.ssh/jellyfish_deploy_key

      - name: Setup SSH config
        shell: bash
        run: |
          touch ~/.ssh/config
          cat << EOF > ~/.ssh/config
          Host github.com-jellyfish
                  Hostname github.com
                  IdentityFile=~/.ssh/jellyfish_deploy_key
          EOF

      # - name: Checkout Jellyfish Repository
      #   id: checkout-jellyfish
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   run: |
      #     git clone git@github.com-jellyfish:Torus-ZK/jellyfish.git

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --all-targets --all-features -- -D warnings

      - name: Cargo Clippy
        uses: actions-rs/clippy-check@v1
        with:
          args: --all --all-targets --all-features -- -D warnings

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Cleanup SSH config
        if: always()
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-add -D
          rm -Rf ~/.ssh/*